spring.application.name=gateway-service
server.port=8080

#Setting Timeout Configuration
spring.cloud.openfeign.client.config.default.connect-timeout=2000
spring.cloud.openfeign.client.config.default.read-timeout=5000

#Setting configuration for Circuit Breaker And Retry

# ================================
# Circuit Breaker - User Service
# ================================

# Minimum number of calls before failure rate is calculated
resilience4j.circuitbreaker.instances.user-service.minimum-number-of-calls=10

# Open circuit when 50% or more calls fail
resilience4j.circuitbreaker.instances.user-service.failure-rate-threshold=50

# Keep circuit OPEN for 10 seconds
resilience4j.circuitbreaker.instances.user-service.wait-duration-in-open-state=10s

# Number of test calls allowed in HALF_OPEN state
resilience4j.circuitbreaker.instances.user-service.permitted-number-of-calls-in-half-open-state=3

# Number of calls stored in the sliding window
resilience4j.circuitbreaker.instances.user-service.sliding-window-size=10

# Count calls based on number of calls
resilience4j.circuitbreaker.instances.user-service.sliding-window-type=COUNT_BASED

# For Logging and status/metrics
resilience4j.circuitbreaker.instances.user-service.register-health-indicator=true
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.level.io.github.resilience4j.retry=DEBUG

# ================================
# Retry - User Service
# ================================

# Maximum number of attempts including the initial call
resilience4j.retry.instances.user-service.max-attempts=3

# Wait 500ms before retrying
resilience4j.retry.instances.user-service.wait-duration=500ms

# Yeh retry ko batata h ke agr exception RetryableException iss se aaye tohi usko retry krna hai
resilience4j.retry.instances.user-service.retry-exceptions=feign.RetryableException


# TimeLimiter
resilience4j.timelimiter.instances.user-service.timeout-duration=3s